INSERT INTO reading_questions (type, title, paragraph, data) VALUES 
('Summary Completion', 'The Siberian Tiger', 
'The Siberian tiger can be found in what was the USSR and seems to live mainly on the lower slopes of mountains. It likes to eat wild boar, wapiti and moose and will travel long distances in search of food. The male tiger weighs more than the female and is bigger than any other species of tiger. Genetically it is closely linked to the now extinct Caspian tiger. Although brown bears are capable of killing tigers, they make up approximately 8% of their diet. Russian conservatives are trying to protect Siberian tigers because they keep the wolf population under control.', 
'[
    {"question": "The main habitat of the Siberian tiger is in low mountainous areas of the former _________.", "correct_answer": "USSR"},
    {"question": "It is similar genetically to the __________.", "correct_answer": "Caspian tiger"},
    {"question": "Russian conservatives want to __________ the number of wolves and protect the Siberian tiger.", "correct_answer": "control"}
]'),

('Summary Completion', 'Do-It-Yourself Products', 
'The instructions accompanying do-it-yourself products are regularly cited as a source of unnecessary expense or frustration. Few companies seem to test their instructions by having them followed by a first-time user. Often, essential information is omitted, steps in the construction process are taken for granted, and some degree of special knowledge is assumed. This is especially worrying in any fields where failure to follow correct procedures can be dangerous. Objections to material in plain English have come mainly from the legal profession. Lawyers point to the risk of ambiguity inherent in the use of everyday language for legal or official documents and draw attention to the need for confidence in legal formulations, which can come only from using language that has been tested in court over the course of centuries.', 
'[
    {"question": "Consumers often complain that they experience a feeling of __________ when trying to put together do-it-yourself products.", "correct_answer": "frustration"},
    {"question": "Few companies seem to test their instructions by having them followed by a __________.", "correct_answer": "first-time user"},
    {"question": "It is especially important that __________ information is not left out in fields where not following correct procedures can be dangerous.", "correct_answer": "essential"},
    {"question": "No assumptions should be made about the consumer having a certain amount of __________.", "correct_answer": "special knowledge"},
    {"question": "Lawyers have raised objections to the use of plain English, feeling that it would result in ambiguity and cause people to lose faith in __________.", "correct_answer": "legal formulations"}
]'),

('Summary Completion', 'Tyes and Greens', 
'Hayles Tye seems to have got its name from a certain John Hayle who is documented in the 1380s, although there are records pointing to the occupation of the site at a much earlier date. The name was still in use in 1500 and crops up again throughout the 16th and 17th centuries, usually in relation to the payment of taxes or tithes. At some point during the 18th century, the name is changed to Filo’a Green, though no trace of an owner called File has been found. Also in the 18th century, the original dwellings on the site disappeared. Much of this region was economically depressed during this period and the land and its dwellings may simply have been abandoned. Several farms were abandoned in the neighbouring village of Alphamstone, and the population dwindled so much that there was no money to support the fabric of the village church, which became very dilapidated. However, another possibility is that the buildings at File’s Green burnt down, fires being not infrequent at this time.', 
'[
    {"question": "1380s- John Hayle, who is __________, apparently gave his name to Hayles Tye.", "correct_answer": "documented"},
    {"question": "In the 1500s, the name of Hayles Tye was still __________.", "correct_answer": "in use"},
    {"question": "The name __________ again throughout the following two centuries in relation to taxes.", "correct_answer": "cropped up"},
    {"question": "In the 18th century, Hayles Tye was renamed __________.", "correct_answer": "Filo’a Green"},
    {"question": "The original dwellings may either have disappeared, or were __________.", "correct_answer": ["burnt down", "abandoned"]}
]'),

('Summary Completion', 'Caveat Scriptor', 
'A. People think that writing as a profession is glamorous; that it is just about sitting down and churning out words on a page, or more likely these days on a computer screen. If only it were! So what exactly does writing a book entail? Being a writer is about managing a galaxy of contradictory feelings. Of course, it also involves carrying out detailed research: first to establish whether there is a market for the planned publication, and second into the content of the book.  Once the publication has been embarked upon, there is a long period of turmoil as the text takes shape. A first draft is rarely the final text of the book. While some people might think that with new technology the checking and editing process is speeded up, the experienced writer would hardly agree.
B. After the trauma of self-editing and looking for howlers, it is time to show the text to other people, friends perhaps, for appraisal. It also helps, at this stage, to offer a synopsis of the book, if it is a novel, or an outline if it is a textbook. The lucky few are taken on by publishers or agents, then have their books subjected to a number of readers, whose job it is to vet a book: deciding whether it is worth publishing and whether the text as it stands is acceptable or not. After a book has finally been accepted by a publisher, one of the greatest difficulties for the writer lies in taking on board the publisher’s alterations to the text. A book’s creation period is complex and unnerving, but the publisher’s reworkings and text amputations can also be a tortuous process. Abandon writing? Nonsense. Once smitten, it is not easy to escape the compulsion to create and write, despite the roller-coaster ride of contradictory emotions.', 
'[
    {"question": "People often associate writing with __________.", "correct_answer": "glamour"},
    {"question": "Being a writer involves managing conflicting emotions as well as __________.", "correct_answer": "research"},
    {"question": "Advanced technology does not make the __________ faster.", "correct_answer": "editing process"},
    {"question": "When a writer has a draft of the text ready, it is a good idea to have a __________ for friends to look at.", "correct_answer": "summary"},
    {"question": "If an author is accepted by a publisher, the draft of the book is given to __________ for vetting.", "correct_answer": "readers"}
]'),

('Summary Completion', 'Dirty River But Clean Water', 
'Floods once raged through the canyon every year. Spring Snow from as far away as Wyoming would melt and swell the Colorado river to a flow that averaged around 1,500 cubic metres (50,000 cubic feet) a second. These floods infused the river with sediment, carved its beaches and built its sandbars. However, in the four decades since the building of the Glen Canyon dam, just upstream of the Grand Canyon, the only sediment that it has collected has come from tiny, undammed tributaries. This lack of flooding has harmed local wildlife. In the years since the Glen Canyon dam was built, several species have vanished altogether. These include the Colorado pike-minnow, the razorback sucker and the round-tail chub. Meanwhile, aliens including fathead minnows, channel catfish and common carp, which would have been hard to survive in the savage waters of the undammed canyon, have moved in. So flooding is the obvious answer. Unfortunately, it is easier said than done. Floods were sent down the Grand Canyon in 1996 and 2004 and the results were mixed. In 1996 the flood was allowed to go on too long. To start with, all seemed well. The floodwaters built up sandbanks and infused the river with sediment.', 
'[
    {"question": "The snow from far Wyoming would melt in the season of __________.", "correct_answer": "spring"},
    {"question": "In the four decades after people built the Glen Canyon Dam, it only gathered __________ from tiny, undammed tributaries.", "correct_answer": "sediment"},
    {"question": "Several species disappeared including Colorado pike-minnow, __________ and the round-tail chub.", "correct_answer": "razorback sucker"},
    {"question": "Some alien species moved in, such as fathead minnows, channel catfish, and __________.", "correct_answer": "common carp"}
]'),

('Summary Completion', 'Mammoth Kill 2', 
'Although it’s hard to imagine in this age of urban sprawl and automobiles, North America once belonged to mammoths, camels, ground sloths as large as cows, bear-sized beavers and other formidable beasts. Some 11,000 years ago, however, these large-bodied mammals and others – about 70 species in all – disappeared. Yet despite decades of scientific investigation, the exact cause remains a mystery. Now new findings offer support to one of these controversial hypotheses: that human hunting drove this megafaunal menagerie to extinction.  The overkill model emerged in the 1960s when it was put forth by Paul S. Martin of the University of Arizona.  A more specific criticism comes from mammalogist Ross D. E. MacPhee of the American Museum of Natural History in New York City, who points out that the relevant archaeological record contains barely a dozen examples of stone points embedded in mammoth bones (and none, it should be noted, are known from other megafaunal remains) – hardly what one might expect if hunting drove these animals to extinction. Furthermore, some of these species had huge ranges – the giant Jefferson’s ground sloth, for example, lived as far north as the Yukon and as far south as Mexico – which would have made slaughtering them in numbers sufficient to cause their extinction rather implausible, he says. 
Rather he suggests that people may have introduced hyper-lethal disease, perhaps through their dogs or hitchhiking vermin, which then spread widely among the immunologically naive species of the New World. Repeated outbreaks of a hyper-disease could thus quickly drive them to the point of no return. So far MacPhee does not have empirical evidence for the hyper-disease hypothesis, and it won’t be easy to come by hyper-lethal disease that would kill far too quickly to leave its signature on the bones themselves.  The third explanation blames the loss on the weather. The Pleistocene epoch witnessed considerable climatic instability, explains palaeontologist Russell W. Graham of the Denver Museum of Nature and Science. As a result, certain habitats disappeared, and species that had once formed communities split apart. For much of the megafauna, however, the increasingly homogeneous environment left them with shrinking geographical ranges – a death sentence for large animals, which need large ranges. Although these creatures managed to maintain viable populations through most of the Pleistocene, the final major fluctuation – the so-called Younger Dryas event – pushed them over the edge.', 
'[
    {"question": "The reason why big-sized mammals became extinct 11,000 years ago is under hot debate. First, the explanation is that __________ of humans made it happen.", "correct_answer": "hunting"},
    {"question": "This so-called __________ began in the 1960s suggested by an expert.", "correct_answer": "overkill model"},
    {"question": "Another assumption promoted by MacPhee is that deadly __________ from humans causes their demises.", "correct_answer": "disease / hyper disease"},
    {"question": "His hypothesis required more __________ to testify its validity.", "correct_answer": "empirical evidence"},
    {"question": "Graham proposed a third hypothesis that __________ in the Pleistocene epoch drove some species to disappear.", "correct_answer": "climatic instability"}
]'),

('Summary Completion', 'Learning By Examples', 
'Learning theory is rooted in the work of Ivan Pavlov, the famous scientist who discovered and documented the principles governing how animals (humans included) learn in the 1900s.  Years of learning research have led to the creation of a highly precise learning theory that can be used to understand and predict how and under what circumstances most any animal will learn, including human beings, and eventually help people figure out how to change their behaviors. A paper in 1996 Animal Behavior by Bednekoff and Balda provides a different view of the adaptiveness of social learning. It concerns the seed caching behavior of Clark’s nutcracker (Nucifraga Columbiana) and the Mexican jay (Aphelocoma ultramarina). The former is a specialist, catching 30,000 or so seeds in scattered locations that it will recover over the months of winter, the Mexican jay will also cache food but is much less dependent upon this than the nutcracker. The two species also differ in their social structure, the nutcracker being rather solitary while the jay forages in social groups. 
The experiment is to discover not just whether a bird can remember where it hid a seed but also if it can remember where it saw another bird hide a seed. The design is slightly comical with a cacher bird wandering about a room with lots of holes in the floor hiding food in some of the holes, while watched by an observer bird perched in a cage. Two days later cachers and observers are tested for their discovery rate against an estimated random performance. In the role of cacher, not only nutcrackers but also the less specialized jay performed above chance; more surprisingly, however, jay observers were as successful as jay cachers whereas nutcracker observers did no better than chance. It seems that, whereas the nutcracker is highly adapted at remembering where it hid its own seeds, the social living Mexican jay is more adept at remembering, and so exploiting, the caches of others.', 
'[
    {"question": "While the Nutcracker is more able to cache seeds, the Jay relies __________ upon caching food.", "correct_answer": "less"},
    {"question": "The Jay is thus less specialized in this ability but more __________.", "correct_answer": "social"},
    {"question": "In the experiment, the cacher bird hid seeds in the ground while the other __________.", "correct_answer": "watched"},
    {"question": "In the experiment, the __________ did better at finding the seeds.", "correct_answer": "observer"},
    {"question": "The observing __________ didn’t do as well as its counterpart.", "correct_answer": "nutcracker"}
]');

