
export const commonWords = {
    "be": ["am", "are", "been", "being", "is", "was", "were"],
    "I": [],
    "you": [],
    "the": [],
    "a": ["an"],
    "to": [],
    "it": [],
    "not": [],
    "that": ["those"],
    "and": [],
    "of": [],
    "do": ["did", "does", "doing", "done"],
    "have": ["had", "has", "having"],
    "what": [],
    "we": [],
    "in": [],
    "get": ["gets", "getting", "got", "gotten"],
    "this": ["these"],
    "my": ["mine"],
    "me": [],
    "go": ["goes", "going", "gone", "went"],
    "oh": [],
    "can": ["could", "cannot"],
    "no": [],
    "on": [],
    "for": [],
    "know": ["knew", "knowing", "known", "knows"],
    "just": [],
    "your": [],
    "'s": ["'"],
    "all": [],
    "so": [],
    "with": [],
    "he": [],
    "but": [],
    "yeah": [],
    "well": [],
    "think": ["thinking", "thinks", "thought"],
    "here": [],
    "want": ["wanted", "wanting", "wants"],
    "out": [],
    "about": [],
    "good": ["better", "best"],
    "come": ["came", "comes", "coming"],
    "up": [],
    "say": ["said", "saying", "says"],
    "now": [],
    "at": [],
    "one": ["ones"],
    "hey": [],
    "they": [],
    "see": ["saw", "seeing", "seen", "sees"],
    "if": [],
    "how": [],
    "like": ["liked", "likes", "liking"],
    "she": [],
    "look": ["looked", "looking", "looks"],
    "make": ["made", "makes", "making"],
    "right": [],
    "guy": ["guys"],
    "take": ["taken", "takes", "taking", "took"],
    "let": ["lets", "letting"],
    "really": [],
    "okay": [],
    "her": [],
    "uh": ["um"],
    "tell": ["telling", "tells", "told"],
    "him": [],
    "why": [],
    "there": [],
    "who": [],
    "time": ["times"],
    "thing": ["things"],
    "from": [],
    "will": ["willing", "would"],
    "like": [],
    "when": [],
    "as": [],
    "because": [],
    "some": [],
    "our": [],
    "yes": [],
    "back": [],
    "mean": ["meaning", "means", "meant"],
    "man": ["men"],
    "little": [],
    "give": ["gave", "given", "gives", "giving"],
    "his": [],
    "us": [],
    "them": [],
    "need": ["needed", "needs", "needing"],
    "then": [],
    "shall": ["should"],
    "or": [],
    "talk": ["talked", "talking", "talks"],
    "something": [],
    "where": [],
    "great": ["greater", "greatest"],
    "way": ["ways"],
    "never": [],
    "call": ["called", "calling", "calls"],
    "too": [],
    "by": [],
    "sorry": [],
    "over": [],
    "love": ["loved", "loves", "loving"],
    "wait": ["waited", "waiting", "waits"],
    "more": [],
    "down": [],
    "day": ["days"],
    "two": ["twos"],
    "people": [],
    "God": [],
    "very": [],
    "off": [],
    "work": ["worked", "working", "works"],
    "thank": ["thanked", "thanking", "thanks"],
    "big": ["bigger", "biggest"],
    "try": ["tried", "tries", "trying"],
    "dad": ["dads"],
    "maybe": [],
    "feel": ["feeling", "feels", "felt"],
    "friend": ["friends"],
    "even": [],
    "sure": ["surer", "surest"],
    "find": ["finding", "finds", "found"],
    "kid": ["kids"],
    "these": [],
    "boy": ["boys"],
    "put": ["puts", "putting"],
    "please": [],
    "happen": ["happened", "happening", "happens"],
    "much": [],
    "stop": ["stopped", "stopping", "stops"],
    "night": ["nights"],
    "bad": ["worse", "worst"],
    "into": [],
    "those": [],
    "any": [],
    "first": [],
    "leave": ["leaves", "leaving", "left"],
    "year": ["years"],
    "hear": ["heard", "hearing", "hears"],
    "ever": [],
    "Mr.": ["Messrs."],
    "again": [],
    "use": ["used", "uses", "using"],
    "mom": ["moms"],
    "may": ["might"],
    "hi": [],
    "life": ["lives"],
    "nice": ["nicer", "nicest"],
    "new": ["newer", "newest"],
    "still": [],
    "kind": ["kinds"],
    "anything": [],
    "only": [],
    "baby": ["babies"],
    "than": [],
    "fine": ["finer", "finest"],
    "hello": [],
    "keep": ["keeping", "keeps", "kept"],
    "girl": ["girls"],
    "help": ["helped", "helping", "helps"],
    "believe": ["believed", "believes", "believing"],
    "woman": ["women"],
    "lot": ["lots"],
    "play": ["played", "playing", "plays"],
    "ask": ["asked", "asking", "asks"],
    "start": ["started", "starting", "starts"],
    "home": ["homes"],
    "nothing": [],
    "hmm": ["hm"],
    "their": ["theirs"],
    "meet": ["meeting", "meets", "met"],
    "huh": [],
    "show": ["showed", "showing", "shown", "shows"],
    "around": [],
    "guess": ["guessed", "guesses", "guessing"],
    "old": ["older", "oldest"],
    "hell": [],
    "before": [],
    "always": [],
    "three": ["threes"],
    "wow": [],
    "listen": ["listened", "listening", "listens"],
    "minute": ["minutes"],
    "actually": [],
    "eat": ["ate", "eaten", "eating", "eats"],
    "place": ["places"],
    "live": ["lived", "lives", "living"],
    "away": [],
    "after": [],
    "bring": ["bringing", "brings", "brought"],
    "every": [],
    "everything": [],
    "money": [],
    "person": ["people", "persons"],
    "watch": ["watched", "watches", "watching"],
    "other": [],
    "remember": ["remembered", "remembering", "remembers"],
    "house": ["houses"],
    "wrong": [],
    "kill": ["killed", "killing", "kills"],
    "school": ["schools"],
    "everyone": [],
    "run": ["ran", "running", "runs"],
    "late": ["later", "latest"],
    "care": ["cared", "cares", "caring"],
    "car": ["cars"],
    "move": ["moved", "moves", "moving"],
    "ah": ["aah"],
    "idea": ["ideas"],
    "another": [],
    "someone": [],
    "today": [],
    "turn": ["turned", "turning", "turns"],
    "real": [],
    "happy": ["happier", "happiest"],
    "whole": [],
    "week": ["weeks"],
    "job": ["jobs"],
    "fun": [],
    "problem": ["problems"],
    "break": ["breaking", "breaks", "broke", "broken"],
    "world": ["worlds"],
    "which": [],
    "must": [],
    "party": ["parties"],
    "buy": ["bought", "buying", "buys"],
    "through": [],
    "together": [],
    "room": ["rooms"],
    "family": ["families"],
    "stay": ["stayed", "staying", "stays"],
    "lose": ["loses", "losing", "lost"],
    "stuff": [],
    "son": ["sons"],
    "stupid": ["stupider", "stupidest"],
    "name": ["names"],
    "everybody": [],
    "last": ["lasted", "lasting", "lasts"],
    "long": ["longer", "longest"],
    "tonight": [],
    "child": ["children"],
    "sit": ["sat", "sits", "sitting"],
    "course": ["courses"],
    "pretty": ["prettier", "prettiest"],
    "hold": ["held", "holding", "holds"],
    "game": ["games"],
    "forget": ["forgets", "forgetting", "forgot", "forgotten"],
    "else": [],
    "own": [],
    "five": ["fives"],
    "second": [],
    "doctor": ["doctors"],
    "dollar": ["dollars"],
    "enough": [],
    "dog": ["dogs"],
    "funny": ["funnier", "funniest"],
    "wear": ["wearing", "wears", "wore", "worn"],
    "die": ["died", "dies", "dying"],
    "sir": ["sirs"],
    "hard": ["harder", "hardest"],
    "honey": [],
    "sound": ["sounded", "sounding", "sounds"],
    "sex": ["sexes"],
    "hate": ["hated", "hates", "hating"],
    "suppose": ["supposed", "supposes", "supposing"],
    "head": ["heads"],
    "understand": ["understanding", "understands", "understood"],
    "whoa": [],
    "movie": ["movies"],
    "worry": ["worried", "worries", "worrying"],
    "cool": ["cooler", "coolest"],
    "marry": ["married", "marries", "marrying"],
    "miss": ["missed", "misses", "missing"],
    "pay": ["paid", "paying", "pays"],
    "hour": ["hours"],
    "crazy": ["crazier", "craziest"],
    "change": ["changed", "changes", "changing"],
    "hot": ["hotter", "hottest"],
    "most": [],
    "excuse": ["excused", "excuses", "excusing"],
    "mother": ["mothers"],
    "check": ["checked", "checking", "checks"],
    "pick": ["picked", "picking", "picks"],
    "word": ["words"],
    "same": ["sameness"],
    "yourself": ["yourselves"],
    "ready": ["readier", "readiest"],
    "seem": ["seemed", "seeming", "seems"],
    "win": ["winning", "wins", "won"],
    "walk": ["walked", "walking", "walks"],
    "father": ["fathers"],
    "story": ["stories"],
    "already": [],
    "hope": ["hoped", "hopes", "hoping"],
    "part": ["parts"],
    "open": ["opened", "opening", "opens"],
    "lady": ["ladies"],
    "read": ["reading", "reads"],
    "drink": ["drank", "drinking", "drinks", "drunk"],
    "sleep": ["sleeping", "sleeps", "slept"],
    "number": ["numbers"],
    "write": ["writes", "writing", "written", "wrote"],
    "morning": ["mornings"],
    "tomorrow": ["tomorrows"],
    "next": [],
    "phone": ["phones", "telephone", "telephones"],
    "four": ["fours"],
    "once": [],
    "somebody": [],
    "probably": [],
    "without": [],
    "many": [],
    "such": [],
    "eye": ["eyes"],
    "drive": ["driven", "drives", "driving", "drove"],
    "wife": ["wives"],
    "book": ["books"],
    "hang": ["hanged", "hanging", "hangs", "hung"],
    "since": [],
    "throw": ["threw", "throwing", "thrown", "throws"],
    "name": ["named", "naming", "names"],
    "dead": [],
    "stand": ["standing", "stands", "stood"],
    "myself": [],
    "aw": [],
    "dinner": ["dinners"],
    "anyone": [],
    "hand": ["hands"],
    "each": [],
    "anyway": [],
    "television": ["televisions"],
    "learn": ["learned", "learning", "learns"],
    "shut": ["shuts", "shutting"],
    "town": ["towns"],
    "beautiful": [],
    "both": [],
    "date": ["dates"],
    "spend": ["spending", "spends", "spent"],
    "office": ["offices"],
    "hit": ["hits", "hitting"],
    "yet": [],
    "save": ["saved", "saves", "saving"],
    "true": ["truer", "truest"],
    "sweet": ["sweeter", "sweetest"],
    "until": [],
    "food": ["foods"],
    "while": [],
    "send": ["sending", "sends", "sent"],
    "high": ["higher", "highest"],
    "anymore": [],
    "also": [],
    "news": [],
    "Christmas": [],
    "ten": [],
    "ass": ["asses"],
    "business": ["businesses"],
    "couple": ["couples"],
    "totally": [],
    "door": ["doors"],
    "gay": ["gayer", "gayest"],
    "exactly": [],
    "parent": ["parents"],
    "few": ["fewer", "fewest"],
    "month": ["months"],
    "easy": ["easier", "easiest"],
    "deal": ["deals"],
    "ow": ["ouch", "yow"],
    "hurt": ["hurting", "hurts"],
    "nobody": [],
    "OK": [],
    "perfect": [],
    "lie": ["lay", "lied", "lies", "lying"],
    "free": ["freer", "freest"],
    "young": ["younger", "youngest"],
    "weird": ["weirder", "weirdest"],
    "whatever": [],
    "brother": ["brothers"],
    "work": ["works"],
    "kidding": ["kidded", "kids"],
    "ago": [],
    "end": ["ended", "ending", "ends"],
    "other": ["others"],
    "ball": ["balls"],
    "finally": [],
    "line": ["lines"],
    "its": [],
    "ha": ["hah"],
    "important": [],
    "fall": ["fallen", "falling", "falls", "fell"],
    "heart": ["hearts"],
    "long": ["longer", "longest"],
    "fat": ["fatter", "fattest"],
    "class": ["classes"],
    "shoot": ["shooting", "shoots", "shot"],
    "picture": ["pictures"],
    "sell": ["sells", "selling", "sold"],
    "side": ["sides"],
    "wish": ["wished", "wishes", "wishing"],
    "love": ["loves"],
    "mind": ["minds"],
    "hair": ["hairs"],
    "cut": ["cuts", "cutting"],
    "wedding": ["weddings"],
    "reason": ["reasons"],
    "become": ["became", "becomes", "becoming"],
    "least": [],
    "look": ["looked", "looking", "looks"],
    "bite": ["bites", "biting", "bit", "bitten"],
    "fuck": ["fucked", "fucking", "fucks"],
    "under": [],
    "bed": ["beds"],
    "paper": ["papers"],
    "different": [],
    "catch": ["catches", "catching", "caught"],
    "mine": [],
    "six": [],
    "set": ["sets", "setting"],
    "face": ["faces"],
    "speak": ["speaks", "speaking", "spoke", "spoken"],
    "suck": ["sucks", "sucking", "sucked"],
    "sometimes": [],
    "city": ["cities"],
    "special": [],
    "stick": ["sticks", "sticking", "stuck"],
    "question": ["questions"],
    "dude": ["dudes"],
    "realize": ["realized", "realizes", "realizing"],
    "birthday": ["birthdays"],
    "point": ["points"],
    "enjoy": ["enjoyed", "enjoying", "enjoys"],
    "fact": ["facts"],
    "dance": ["danced", "dances", "dancing"],
    "soon": [],
    "bar": ["bars"],
    "wonder": ["wondered", "wondering", "wonders"],
    "joke": ["jokes"],
    "relationship": ["relationships"],
    "chance": ["chances"],
    "black": ["blacker", "blackest"],
    "almost": [],
    "fight": ["fights", "fighting", "fought"],
    "card": ["cards"],
    "song": ["songs"],
    "little": [],
    "bye": ["bye"],
    "coffee": ["coffees"],
    "awesome": [],
    "sick": ["sicker", "sickest"],
    "apartment": ["apartments"],
    "sorry": [],
    "back": ["backs"],
    "figure": ["figured", "figures", "figuring"],
    "pull": ["pulled", "pulling", "pulls"],
    "box": ["boxes"],
    "dream": ["dreams"],
    "water": ["waters"],
    "decide": ["decided", "decides", "deciding"],
    "store": ["stores"],
    "bet": ["bets", "betting"],
    "lunch": ["lunches"],
    "face": ["faces", "facing", "faced"],
    "anybody": [],
    "afraid": [],
    "buddy": ["buddies"],
    "cute": ["cuter", "cutest"],
    "close": ["closer", "closest"],
    "bathroom": ["bathrooms"],
    "mind": ["minded", "minding", "minds"],
    "steal": ["steals", "stealing", "stole", "stolen"],
    "full": ["fuller", "fullest"],
    "company": ["companies"],
    "front": ["fronts"],
    "ahead": [],
    "moment": ["moments"],
    "case": ["cases"],
    "date": ["dated", "dates", "dating"],
    "though": ["tho"],
    "body": ["bodies"],
    "Mrs.": ["Mmes."],
    "pants": [],
    "bitch": ["bitches"],
    "promise": ["promises", "promising", "promised"],
    "glad": ["gladder", "gladdest"],
    "kiss": ["kissed", "kisses", "kissing"],
    "either": [],
    "fire": ["fires", "firing", "fired"],
    "grow": ["grows", "growing", "grew", "grown"],
    "build": ["builds", "building", "built"],
    "table": ["tables"],
    "ticket": ["tickets"],
    "matter": ["matters", "mattering", "mattered"],
    "teach": ["teaches", "teaching", "taught"],
    "cat": ["cats"],
    "sister": ["sisters"],
    "girlfriend": ["girlfriends"],
    "hat": ["hats"],
    "touch": ["touches", "touching", "touched"],
    "terrible": [],
    "beer": ["beers"],
    "damn": [],
    "club": ["clubs"],
    "amaze": ["amazes", "amazing", "amazed"],
    "smell": ["smells", "smelling", "smelled", "smelt"],
    "gift": ["gifts"],
    "serious": [],
    "plan": ["plans", "planning", "planned"],
    "street": ["streets"],
    "team": ["teams"],
    "order": ["orders", "ordering", "ordered"],
    "cry": ["cries", "crying", "cried"],
    "zero": [],
    "drop": ["drops", "dropping", "dropped"],
    "act": ["acts", "acting", "acted"],
    "alone": [],
    "seat": ["seats"],
    "eh": [],
    "between": [],
    "eight": [],
    "twenty": [],
    "foot": ["feet"],
    "seven": [],
    "finish": ["finishes", "finishing", "finished"],
    "gentleman": ["gentlemen"],
    "handing": ["handed", "hands"],
    "point": ["points", "pointing", "pointed"],
    "blow": ["blows", "blowing", "blew", "blown"],
    "small": ["smaller", "smallest"],
    "trouble": ["troubles"],
    "sweetie": ["sweeties"],
    "sing": ["sings", "singing", "sang", "sung"],
    "pass": ["passes", "passing", "passed"],
    "beat": ["beats", "beating", "beaten"],
    "piece": ["pieces"],
    "shoe": ["shoes"],
    "welcome": [],
    "god": ["gods"],
    "white": ["whiter", "whitest"],
    "kick": ["kicks", "kicking", "kicked"],
    "bag": ["bags"],
    "early": ["earlier", "earliest"],
    "excite": ["excites", "exciting", "excited"],
    "wonderful": [],
    "seriously": [],
    "country": ["countries"],
    "mouth": ["mouths"],
    "questioning": ["questions", "questioned"],
    "dear": ["dearer", "dearest"],
    "smart": ["smarter", "smartest"],
    "husband": ["husbands"],
    "invite": ["invites", "inviting", "invited"],
    "rest": ["rests"],
    "yours": [],
    "behind": [],
    "key": ["keys"],
    "end": ["ends"],
    "dress": ["dresses", "dressing", "dressed"],
    "red": ["redder", "reddest"],
    "laugh": ["laughs", "laughing", "laughed"],
    "agree": ["agrees", "agreeing", "agreed"],
    "machine": ["machines"],
    "yep": [],
    "return": ["returns", "returning", "returned"],
    "space": ["spaces"],
    "mad": ["madder", "maddest"],
    "truth": ["truths"],
    "ice": ["ices"],
    "follow": ["follows", "following", "followed"],
    "outside": [],
    "idiot": ["idiots"],
    "rule": ["rules"],
    "absolutely": [],
    "against": [],
    "need": ["needs"],
    "scare": ["scares", "scaring", "scared"],
    "notice": ["notices", "noticing", "noticed"],
    "chicken": ["chickens"],
    "ride": ["rides", "riding", "rode", "ridden"],
    "music": [],
    "join": ["joins", "joining", "joined"],
    "good-bye": ["goodbye"],
    "ruin": ["ruins", "ruining", "ruined"],
    "war": ["wars"],
    "screw": ["screws", "screwing", "screwed"],
    "light": ["lights"],
    "along": [],
    "poor": ["poorer", "poorest"],
    "sense": ["senses"],
    "able": ["abler", "ablest"],
    "secret": ["secrets"],
    "fly": ["flies", "flying", "flew", "flown"],
    "top": ["tops"],
    "sure": [],
    "fair": ["fairer", "fairest"],
    "relax": ["relaxes", "relaxing", "relaxed"],
    "boyfriend": ["boyfriends"],
    "mistake": ["mistakes"],
    "luck": [],
    "group": ["groups"],
    "daughter": ["daughterly", "daughters"],
    "college": ["colleges"],
    "president": ["presidents"],
    "farther": ["farther", "further", "farthest", "furthest"],
    "sign": ["signs", "signing", "signed"],
    "close": ["closes", "closing", "closed"],
    "message": ["messages"],
    "freak": ["freaks", "freaking", "freaked"],
    "fault": ["faulted", "faulting", "faultless", "faultlessly", "faultlessness", "faults"],
    "quick": ["quicker", "quickest"],
    "till": [],
    "except": [],
    "single": [],
    "shirt": ["shirts"],
    "choice": ["choices"],
    "attention": [],
    "power": ["powers"],
    "quit": ["quits", "quitting", "quitted"],
    "answer": ["answers"],
    "trust": ["trusts", "trusting", "trusted"],
    "fifty": ["fifties"],
    "leg": ["legs"],
    "wake": ["wakes", "waking", "waked", "woke", "woken"],
    "human": [],
    "star": ["stars"],
    "student": ["students"],
    "air": ["airs"],
    "chair": ["chairs"],
    "gun": ["guns"],
    "begin": ["begins", "beginning", "began", "begun"],
    "death": ["deaths"],
    "tree": ["trees"],
    "boss": ["bosses"],
    "while": ["whiles"],
    "present": ["presents"],
    "instead": [],
    "lucky": ["luckier", "luckiest"],
    "safe": ["safer", "safest"],
    "cold": ["colder", "coldest"],
    "ahh": [],
    "explain": ["explains", "explaining", "explained"],
    "video": ["videos"],
    "brain": ["brains"],
    "completely": [],
    "voice": ["voices"],
    "cake": ["cakes"],
    "drink": ["drinks"],
    "trip": ["trips"],
    "monkey": ["monkeys"],
    "hundred": ["hundreds"],
    "fix": ["fixes", "fixing", "fixed"],
    "entire": [],
    "expect": ["expected", "expecting", "expects"],
    "million": ["millions"],
    "allow": ["allows", "allowing", "allowed"],
    "forever": [],
    "ugh": [],
    "hide": ["hides", "hiding", "hid", "hidden"],
    "huge": ["huger", "hugest"],
    "interesting": [],
    "roll": ["rolls", "rolling", "rolled"],
    "clothes": [],
    "fast": ["faster", "fastest"],
    "grab": ["grabs", "grabbing", "grabbed"],
    "teacher": ["teachers"],
    "crap": ["craps"],
    "animal": ["animals"],
    "burn": ["burns", "burning", "burned", "burnt"],
    "tough": ["tougher", "toughest"],
    "restaurant": ["restaurants"],
    "sort": ["sorts"],
    "tooth": ["teeth"],
    "marriage": ["marriages"],
    "proud": ["prouder", "proudest"],
    "uncle": ["uncles"],
    "push": ["pushes", "pushing", "pushed"],
    "butt": ["butts"],
    "offer": ["offers", "offering", "offered"],
    "lord": ["lords"],
    "unless": [],
    "feeling": ["feelings"],
    "suit": ["suits"],
    "uh-huh": [],
    "floor": ["floors"],
    "cream": ["creams"],
    "favorite": [],
    "naked": [],
    "list": ["lists"],
    "ring": ["rings"],
    "clean": ["cleans", "cleaning", "cleaned"],
    "apologize": ["apologizing", "apologizes", "apologized"],
    "clear": ["clearer", "clearest"],
    "Earth": ["earth"],
    "share": ["shares", "sharing", "shared"],
    "fill": ["fills", "filling", "filled"],
    "cool": [],
    "pizza": ["pizzas"],
    "ridiculous": [],
    "alive": [],
    "pretend": ["pretends", "pretending", "pretended"],
    "hospital": ["hospitals"],
    "sad": ["sadder", "saddest"],
    "bunch": ["bunches"],
    "half": [],
    "police": [],
    "fish": ["fishes"],
    "window": ["windows"],
    "busy": ["busier", "busiest"],
    "sign": ["signs"],
    "call": ["calls"],
    "pie": ["pies"],
    "raise": ["raises", "raising", "raised"],
    "somewhere": [],
    "sandwich": ["sandwiches"],
    "thirty": ["thirties"],
    "sale": ["sales"],
    "choose": ["chooses", "choosing", "chose", "chosen"],
    "definitely": [],
    "swear": ["swears", "swearing", "swore", "sworn"],
    "pretty": [],
    "boat": ["boats"],
    "tired": [],
    "upset": [],
    "less": [],
    "nine": ["nines"],
    "thousand": ["thousands"],
    "smoke": ["smokes", "smoking", "smoked"],
    "embarrass": ["embarrasses", "embarrassing", "embarrassed"],
    "band": ["bands"],
    "bear": ["bears", "bearing", "bore", "borne", "born"],
    "none": [],
    "Santa": [],
    "strong": ["stronger", "strongest"],
    "law": ["laws"],
    "toilet": ["toilets"],
    "jump": ["jumps", "jumping", "jumped"],
    "count": ["counts", "counting", "counted"],
    "egg": ["eggs"],
    "Saturday": ["Saturdays"],
    "blue": ["bluer", "bluest"],
    "horrible": [],
    "shit": ["shits"],
    "favor": ["favors"],
    "handle": ["handles", "handling", "handled"],
    "wall": ["walls"],
    "art": ["arts"],
    "cover": ["covers", "covering", "covered"],
    "arm": ["arms"],
    "perhaps": [],
    "simple": ["simpler", "simplest"],
    "bus": ["buses"],
    "appreciate": ["appreciates", "appreciating", "appreciated"],
    "himself": [],
    "surprise": ["surprises", "surprising", "surprised"],
    "candy": ["candies"],
    "finger": ["fingers"],
    "worth": [],
    "state": ["states"],
    "possible": [],
    "rich": ["richer", "richest"],
    "short": ["shorter", "shortest"],
    "king": ["kings"],
    "knock": ["knocks", "knocking", "knocked"],
    "cookie": ["cookies"],
    "penis": ["penises", "penes"],
    "history": ["histories"],
    "imagine": ["imagines", "imagining", "imagined"],
    "third": ["thirds"],
    "blood": ["bloods"],
    "drug": ["drugs"],
    "future": ["futures"],
    "prove": ["proves", "proving", "proved", "proven"],
    "surprise": ["surprises"],
    "alright": [],
    "captain": ["captains"],
    "evening": ["evenings"],
    "congratulations": [],
    "system": ["systems"],
    "record": ["records"],
    "age": ["ages"],
    "deserve": ["deserves", "deserving", "deserved"],
    "normal": [],
    "yesterday": ["yesterdays"],
    "jerk": ["jerks"],
    "yay": [],
    "bird": ["birds"],
    "nose": ["noses"],
    "bother": ["bothers", "bothering", "bothered"],
    "fan": ["fans"],
    "letter": ["letters"],
    "rather": [],
    "head": ["heads", "heading", "headed"],
    "interested": [],
    "owe": ["owes", "owing", "owed"],
    "pregnant": [],
    "destroy": ["destroys", "destroying", "destroyed"],
    "bear": ["bears"],
    "evil": ["eviler", "eviller", "evilest", "evillest"],
    "milk": ["milks"],
    "sport": ["sports"],
    "admit": ["admits", "admitting", "admitted"],
    "apparently": [],
    "conversation": ["conversations"],
    "obviously": [],
    "uh-oh": [],
    "jacket": ["jackets"],
    "during": [],
    "accept": ["accepts", "accepting", "accepted"],
    "dumb": ["dumber", "dumbest"],
    "bit": ["bits"],
    "consider": ["considers", "considering", "considered"],
    "mention": ["mentions", "mentioning", "mentioned"],
    "step": ["steps", "stepping", "stepped"],
    "deal": ["deals", "dealing", "dealt"],
    "hungry": ["hungrier", "hungriest"],
    "situation": ["situations"],
    "lead": ["leads", "leading", "leaded", "led"],
    "twelve": ["twelves"],
    "fantastic": [],
    "hole": ["holes"],
    "plus": [],
    "note": ["notes"],
    "test": ["tests"],
    "honest": ["honester", "honestest"],
    "character": ["characters"],
    "holy": ["holier", "holiest"],
    "manager": ["managers"],
    "lesson": ["lessons"],
    "soul": ["souls"],
    "nope": [],
    "dark": ["darker", "darkest"],
    "difference": ["differences"],
    "wine": ["wines"],
    "road": ["roads"],
    "calm": ["calms", "calming", "calmed"],
    "personal": [],
    "clown": ["clowns"],
    "computer": ["computers"],
    "horse": ["horses"],
    "gosh": [],
    "mayor": ["mayors"],
    "inside": [],
    "sexy": ["sexier", "sexiest"],
    "dirty": ["dirtier", "dirtiest"],
    "carry": ["carries", "carrying", "carried"],
    "professor": ["professors"],
    "usually": [],
    "bottle": ["bottles"],
    "cheese": ["cheeses"],
    "summer": ["summers"],
    "remind": ["reminds", "reminding", "reminded"],
    "afternoon": ["afternoons"],
    "pee": ["pees", "peeing", "peed"],
    "across": [],
    "angry": ["angrier", "angriest"],
    "fella": ["fellas"],
    "film": ["films"],
    "reach": ["reaches", "reaching", "reached"],
    "shower": ["showers"],
    "cup": ["cups"],
    "lawyer": ["lawyers"],
    "camera": ["cameras"],
    "pain": ["pains"],
    "hurry": ["hurries", "hurrying", "hurried"],
    "desk": ["desks"],
    "monster": ["monsters"],
    "certainly": [],
    "cop": ["cops"],
    "credit": ["credits"],
    "prepare": ["prepares", "preparing", "prepared"],
    "anywhere": [],
    "breakfast": ["breakfasts"],
    "bastard": ["bastards"],
    "damn": [],
    "church": ["churches"],
    "hire": ["hires", "hiring", "hired"],
    "decision": ["decisions"],
    "pig": ["pigs"],
    "loser": ["losers"],
    "robot": ["robots"],
    "deep": ["deeper", "deepest"],
    "park": ["parks"],
    "chocolate": ["chocolates"],
    "service": ["services"],
    "Jew": [],
    "tape": ["tapes"],
    "kitchen": ["kitchens"],
    "half": ["halves"],
    "rid": ["rids", "ridding", "ridded"],
    "grandpa": ["grandpas"],
    "hero": ["heroes"],
    "shot": ["shots"],
    "spot": ["spots"],
    "folks": [],
    "yell": ["yells", "yelling", "yelled"],
    "awful": ["awfuller", "awfullest"],
    "scene": ["scenes"],
    "trick": ["tricks"],
    "asshole": ["assholes"],
    "issue": ["issues"],
    "lovely": ["lovelier", "loveliest"],
    "visit": ["visits", "visiting", "visited"],
    "honor": ["honors"],
    "clean": ["cleaner", "cleanest"],
    "second": ["seconds"],
    "chick": ["chicks"],
    "costume": ["costumes"],
    "Friday": ["Fridays"],
    "hall": ["halls"],
    "Ms": ["Mss", "Mses"],
    "fake": [],
    "forgive": ["forgives", "forgiving", "forgave", "forgiven"],
    "grade": ["grades"],
    "fifteen": ["fifteens"],
    "ought": [],
    "cheat": ["cheats", "cheating", "cheated"],
    "Chinese": [],
    "crap": ["craps", "crapping", "crapped"],
    "create": ["creates", "creating", "created"],
    "comfortable": [],
    "hotel": ["hotels"],
    "magazine": ["magazines"],
    "settle": ["settles", "settling", "settled"],
    "accident": ["accidents"],
    "boob": ["boobs"],
    "excellent": [],
    "neighbor": ["neighbors"],
    "train": ["trains"],
    "board": ["boards"],
    "pop": ["pops", "popping", "popped"],
    "spirit": ["spirits"],
    "cow": ["cows"],
    "building": ["buildings"],
    "ear": ["ears"],
    "giant": ["giants"],
    "ugly": ["uglier", "ugliest"],
    "toy": ["toys"],
    "cancel": ["cancels", "canceling", "canceled"],
    "Internet": ["Net"],
    "strange": ["stranger", "strangest"],
    "aunt": ["aunts"],
    "island": ["islands"],
    "extra": [],
    "fit": ["fits", "fitting", "fitted"],
    "rock": ["rocks"],
    "action": ["actions"],
    "bill": ["bills"],
    "field": ["fields"],
    "fresh": ["fresher", "freshest"],
    "level": ["levels"],
    "cost": ["costs", "costing", "costed"],
    "size": ["sizes"],
    "cell": ["cells"],
    "serve": ["serves", "serving", "served"],
    "shake": ["shakes", "shaking", "shook", "shaken"],
    "neck": ["necks"],
    "bowl": ["bowls"],
    "control": ["controls", "controlling", "controlled"],
    "loud": ["louder", "loudest"],
    "bedroom": ["bedrooms"],
    "check": ["checks"],
    "heaven": ["heavens"],
    "right": ["rights"],
    "commercial": ["commercials"],
    "draw": ["draws", "drawing", "drew", "drawn"],
    "guest": ["guests"],
    "insane": ["insaner", "insanest"],
    "fail": ["fails", "failing", "failed"],
    "cook": ["cooks", "cooking", "cooked"],
    "pleasure": ["pleasures"],
    "truck": ["trucks"],
    "science": ["sciences"],
    "careful": [],
    "nervous": [],
    "although": ["altho"],
    "gas": ["gases", "gasses"],
    "partner": ["partners"],
    "ew": ["eww"],
    "scream": ["screams", "screaming", "screamed"],
    "pool": ["pools"],
    "appear": ["appears", "appearing", "appeared"],
    "clearly": [],
    "silly": ["sillier", "silliest"],
    "feed": ["feeds", "feeding", "fed"],
    "charge": ["charges"],
    "neither": [],
    "wash": ["washes", "washing", "washed"],
    "stink": ["stinks", "stinking", "stank", "stunk"],
    "magic": [],
    "plane": ["planes"],
    "tiny": ["tinier", "tiniest"],
    "prison": ["prisons"],
    "cause": ["causes", "causing", "caused"],
    "photo": ["photos", "photograph", "photographs"],
    "public": [],
    "button": ["buttons"],
    "flower": ["flowers"],
    "memory": ["memories"],
    "own": ["owns", "owning", "owned"],
    "base": ["bases", "basing", "based"],
    "involve": ["involves", "involving", "involved"],
    "madam": ["madams", "mesdames", "ma'am"],
    "blame": ["blames", "blaming", "blamed"],
    "tea": ["teas"],
    "whoo": [],
    "bike": ["bikes"],
    "freeze": ["freezes", "freezing", "froze", "frozen"],
    "sexual": [],
    "code": ["codes"],
    "celebrate": ["celebrates", "celebrating", "celebrated"],
    "couch": ["couches"],
    "price": ["prices"],
    "assume": ["assumes", "assuming", "assumed"],
    "delicious": [],
    "forty": ["forties"],
    "player": ["players"],
    "soup": ["soups"],
    "waste": ["wastes", "wasting", "wasted"],
    "coat": ["coats"],
    "doll": ["dolls"],
    "security": ["securities"],
    "warm": ["warmer", "warmest"],
    "football": ["footballs"],
    "model": ["models"],
    "whose": [],
    "besides": [],
    "middle": ["middles"],
    "shop": ["shops", "shopping", "shopped"],
    "garbage": [],
    "client": ["clients"],
    "ground": [],
    "lame": ["lamer", "lamest"],
    "project": ["projects"],
    "dare": ["dares", "daring", "dared"],
    "episode": ["episodes"],
    "glass": ["glasses"],
    "green": ["greener", "greenest"],
    "lock": ["locks", "locking", "locked"],
    "award": ["awards"],
    "straight": ["straighter", "straightest"],
    "unbelievable": [],
    "court": ["courts"],
    "experience": ["experiences"],
    "final": [],
    "large": ["larger", "largest"],
    "salad": ["salads"],
    "belong": ["belongs", "belonging", "belonged"],
    "fuck": ["fucks"],
    "station": ["stations"],
    "area": ["areas"],
    "vote": ["votes", "voting", "voted"],
    "crime": ["crimes"],
    "meat": ["meats"],
    "romantic": [],
    "treat": ["treats", "treating", "treated"],
    "forward": [],
    "glasses": [],
    "lie": ["lies"],
    "taste": ["tastes", "tasting", "tasted"],
    "weight": ["weights"],
    "mail": ["mails"],
    "cab": ["cabs"],
    "boring": [],
    "information": [],
    "total": [],
    "channel": ["channels"],
    "page": ["pages"],
    "suddenly": [],
    "sake": ["sakes"],
    "Thanksgiving": ["thanksgiving", "thanksgivings"],
    "private": [],
    "French": [],
    "winner": ["winners"],
    "past": ["pasts"],
    "pen": ["pens"],
    "twice": [],
    "cousin": ["cousins"],
    "jealous": [],
    "mess": ["messes", "messing", "messed"],
    "planet": ["planets"],
    "scary": ["scarier", "scariest"],
    "universe": ["universes"],
    "upstairs": [],
    "genius": ["geniuses", "genii"],
    "dangerous": [],
    "nuts": [],
    "ourselves": [],
    "race": ["races"],
    "suggest": ["suggests", "suggesting", "suggested"],
    "turn": ["turns"],
    "sea": ["seas"],
    "officer": ["officers"],
    "meal": ["meals"],
    "popular": [],
    "report": ["reports"],
    "welcome": [],
    "flight": ["flights"],
    "change": ["changes"],
    "driver": ["drivers"],
    "wheel": ["wheels"],
    "dump": ["dumps", "dumping", "dumped"],
    "five hundred": [],
    "member": ["members"],
    "yo": [],
    "add": ["adds", "adding", "added"],
    "confuse": ["confuses", "confusing", "confused"],
    "form": ["forms"],
    "government": ["governments"],
    "Sunday": ["Sundays"],
    "order": ["orders"],
    "continue": ["continues", "continuing", "continued"],
    "event": ["events"],
    "quiet": ["quieter", "quietest"],
    "low": ["lower", "lowest"],
    "color": ["colors"],
    "Jewish": [],
    "nah": [],
    "breast": ["breasts"],
    "bank": ["banks"],
    "parking": ["parkings"],
    "wild": ["wilder", "wildest"],
    "turkey": ["turkeys"],
    "blah": [],
    "thought": ["thoughts"],
    "famous": [],
    "gold": ["golds"],
    "pound": ["pounds"],
    "skin": ["skins"],
    "one hundred": [],
    "rat": ["rats"],
    "switch": ["switches", "switching", "switched"],
    "tie": ["ties"],
    "career": ["careers"],
    "juice": ["juices"],
    "like": [],
    "protect": ["protects", "protecting", "protected"],
    "shame": ["shames"],
    "bottom": ["bottoms"],
    "respect": ["respects", "respecting", "respected"],
    "underwear": ["underwears"],
    "Indian": [],
    "closet": ["closets"],
    "meeting": ["meetings"],
    "sun": ["suns"],
    "afford": ["affords", "affording", "afforded"],
    "bald": ["balder", "baldest"],
    "engage": ["engages", "engaging", "engaged"],
    "plant": ["plants"],
    "towel": ["towels"],
    "mall": ["malls"],
    "regular": [],
    "bone": ["bones"],
    "dig": ["digs", "digging", "dug"],
    "fear": ["fears"],
    "cancer": ["cancers"],
    "discuss": ["discusses", "discussing", "discussed"],
    "fancy": ["fancier", "fanciest"],
    "control": ["controls", "controlling", "controlled"],
    "advice": [],
    "center": ["centers"],
    "apple": ["apples"],
    "everywhere": [],
    "holiday": ["holidays"],
    "cash": [],
    "common": ["commoner", "commonest"],
    "crush": ["crushes"],
    "mess": ["messes"],
    "peace": [],
    "warn": ["warns", "warning", "warned"],
    "adult": ["adults"],
    "noise": ["noises"],
    "rock": ["rocks", "rocking", "rocked"],
    "super": [],
    "bread": ["breads"],
    "fucking": [],
    "porn": ["porns"],
    "three hundred": [],
    "type": ["types"],
    "borrow": ["borrows", "borrowing", "borrowed"],
    "department": ["departments"],
    "plate": ["plates"],
    "breathe": ["breathes", "breathing", "breathed"],
    "classic": [],
    "farm": ["farms"],
    "disgusting": [],
    "tall": ["taller", "tallest"],
    "replace": ["replaces", "replacing", "replaced"],
    "somehow": [],
    "theater": ["theaters"],
    "discover": ["discovers", "discovering", "discovered"],
    "incredible": [],
    "plenty": ["plenties"],
    "baseball": ["baseballs"],
    "comedy": ["comedies"],
    "enter": ["enters", "entering", "entered"],
    "introduce": ["introduces", "introducing", "introduced"],
    "whenever": [],
    "butter": [],
    "possibly": [],
    "sweetheart": ["sweethearts"],
    "jail": ["jails"],
    "season": ["seasons"],
    "study": ["studies", "studying", "studied"],
    "miracle": ["miracles"],
    "complete": ["completer", "completest"],
    "golf": [],
    "hook": ["hooks", "hooking", "hooked"],
    "perfectly": [],
    "stare": ["stares", "staring", "stared"],
    "flag": ["flags"],
    "jeez": ["geez"],
    "roommate": ["roommates"],
    "ship": ["ships"],
    "wood": ["woods"],
    "actor": ["actors"],
    "prize": ["prizes"],
    "corner": ["corners"],
    "fourth": ["fourths"],
    "sneak": ["sneaks", "sneaking", "sneaked", "snuck"],
    "piss": ["pisses", "pissing", "pissed"],
    "pocket": ["pockets"],
    "lately": [],
    "queen": ["queens"],
    "tear": ["tears", "tearing", "tore", "torn"],
    "especially": [],
    "lay": ["lays", "laying", "laid"],
    "pressure": ["pressures"],
    "rip": ["rips", "ripping", "ripped"],
    "assistant": ["assistants"],
    "camp": ["camps"],
    "judge": ["judges"],
    "North": ["north"],
    "often": ["oftener", "oftenest"],
    "Halloween": ["Halloweens"],
    "vacation": ["vacations"],
    "impossible": [],
    "square": ["squares"],
    "left": ["lefts"],
    "grandma": ["grandmas"],
    "gross": ["grosser", "grossest"],
    "pal": ["pals"],
    "smile": ["smiles", "smiling", "smiled"],
    "speech": ["speeches"],
    "bust": ["busts", "busting", "busted"],
    "gee": [],
    "handsome": ["handsomer", "handsomest"],
    "safety": ["safeties"],
    "test": ["tests", "testing", "tested"],
    "community": ["communities"],
    "beach": ["beaches"],
    "gym": ["gyms"],
    "toast": ["toasts"],
    "disease": ["diseases"],
    "paint": ["paints", "painting", "painted"],
    "themselves": [],
    "Monday": ["Mondays"],
    "pack": ["packs", "packing", "packed"],
    "punch": ["punches", "punching", "punched"],
    "customer": ["customers"],
    "healthy": ["healthier", "healthiest"],
    "invent": ["invents", "inventing", "invented"],
    "princess": ["princesses"],
    "merry": ["merrier", "merriest"],
    "someday": [],
    "blind": ["blinder", "blindest"],
    "certain": [],
    "solve": ["solves", "solving", "solved"],
    "study": ["studies"],
    "sweater": ["sweaters"],
    "terrific": [],
    "wet": ["wetter", "wettest"],
    "attack": ["attacks"],
    "beg": ["begs", "begging", "begged"],
    "cigarette": ["cigaret", "cigarettes", "cigarets"],
    "sugar": ["sugars"],
    "uhh": [],
    "weekend": ["weekends"],
    "sock": ["socks", "sox"],
    "emergency": ["emergencies"],
    "mood": ["moods"],
    "peanut": ["peanuts"],
    "stage": ["stages"],
    "tight": ["tighter", "tightest"],
    "gum": ["gums"],
    "moon": ["moons"],
    "nature": ["natures"],
    "program": ["programs"],
    "straight": [],
    "angel": ["angels"],
    "corporate": [],
    "exist": ["exists", "existing", "existed"],
    "ghost": ["ghosts"],
    "sauce": ["sauces"],
    "stomach": ["stomachs"],
    "twenty-five": [],
    "block": ["blocks"],
    "herself": [],
    "murder": ["murders"],
    "speed": ["speeds"],
    "Jesus": [],
    "mix": ["mixes", "mixing", "mixed", "mixt"],
    "track": ["tracks"],
    "opportunity": ["opportunities"],
    "society": ["societies"],
    "whoo-hoo": [],
    "upon": [],
    "difficult": [],
    "killer": ["killers"],
    "lip": ["lips"],
    "market": ["markets"],
    "goodness": [],
    "pillow": ["pillows"],
    "tie": ["ties", "tying", "tied"],
    "arrive": ["arrives", "arriving", "arrived"],
    "mountain": ["mountains"],
    "slip": ["slips", "slipping", "slipped"],
    "belt": ["belts"],
    "museum": ["museums", "musea"],
    "oil": ["oils"],
    "press": ["presses", "pressing", "pressed"],
    "airplane": ["airplanes"],
    "airport": ["airports"],
    "honestly": [],
    "contest": ["contests"],
    "fabulous": [],
    "spell": ["spells", "spelling", "spelled", "spelt"],
    "whoever": ["whomever"],
    "bell": ["bells"],
    "friendship": ["friendships"],
    "national": [],
    "alien": ["aliens"],
    "dream": ["dreams", "dreaming", "dreamed", "dreamt"],
    "fool": ["fools"],
    "past": [],
    "bless": ["blesses", "blessing", "blessed", "blest"],
    "cartoon": ["cartoons"],
    "near": [],
    "swim": ["swims", "swimming", "swam", "swum"],
    "burger": ["burgers"],
    "fruit": ["fruits"],
    "roof": ["roofs"],
    "theory": ["theories"],
    "according": [],
    "guilty": ["guiltier", "guiltiest"],
    "potato": ["potatoes"],
    "dish": ["dishes"],
    "sound": ["sounds"],
    "uncomfortable": [],
    "wrap": ["wraps", "wrapping", "wrapped", "wrapt"],
    "cheap": ["cheaper", "cheapest"],
    "employee": ["employe", "employees", "employes"],
    "interview": ["interviews"],
    "perform": ["performs", "performing", "performed"],
    "spring": ["springs"],
    "text": ["texts", "texting", "texted"],
    "tour": ["tours"],
    "awkward": ["awkwarder", "awkwardest"],
    "expensive": [],
    "unfortunately": [],
    "purse": ["purses"],
    "charge": ["charges", "charging", "charged"],
    "ha-ha": [],
    "divorce": ["divorces"],
    "ring": ["rings", "ringing", "rang", "rung"],
    "bra": ["bras"],
    "brown": ["browner", "brownest"],
    "duck": ["ducks"],
    "English": [],
    "celebrity": ["celebrities"],
    "double": [],
    "period": ["periods"],
    "rent": ["rents", "renting", "rented"],
    "barely": [],
    "bye-bye": [],
    "chip": ["chips"],
    "ignore": ["ignores", "ignoring", "ignored"],
    "language": ["languages"],
    "laundry": ["laundries"],
    "social": [],
    "soft": ["softer", "softest"],
    "apology": ["apologies"],
    "concert": ["concerts"],
    "disappoint": ["disappoints", "disappointing", "disappointed"],
    "knife": ["knives"],
    "hilarious": [],
    "judge": ["judges", "judging", "judged"],
    "blanket": ["blankets"],
    "comic": [],
    "leader": ["leaders"],
    "local": [],
    "neighborhood": ["neighborhoods"],
    "trap": ["traps", "trapping", "trapped"],
    "West": ["west"],
    "bury": ["buries", "burying", "buried"],
    "whore": ["whores"],
    "cross": ["crosses", "crossing", "crossed"],
    "sheet": ["sheets"],
    "suffer": ["suffers", "suffering", "suffered"],
    "tax": ["taxes"],
    "bath": ["baths"],
    "receive": ["receives", "receiving", "received"],
    "sometime": [],
    "split": ["splits", "splitting"],
    "soda": ["sodas"],
    "talent": ["talents"],
    "account": ["accounts"],
    "convince": ["convinces", "convincing", "convinced"],
    "dessert": ["desserts"],
    "purpose": ["purposes"],
    "weak": ["weaker", "weakest"],
    "cheer": ["cheers", "cheering", "cheered"],
    "support": ["supports", "supporting", "supported"],
    "research": ["researches"],
    "tongue": ["tongues"],
    "Valentine": ["valentine", "valentines"],
    "pill": ["pills"],
    "snake": ["snakes"],
    "battle": ["battles"],
    "license": ["licenses"],
    "nut": ["nuts"],
    "health": [],
    "natural": [],
    "gorgeous": [],
    "steak": ["steaks"],
    "vagina": ["vaginas", "vaginae"],
    "audience": ["audiences"],
    "knee": ["knees"],
    "term": ["terms"],
    "score": ["scores"],
    "sue": ["sues", "suing", "sued"],
    "whether": [],
    "artist": ["artists"],
    "bang": ["bangs", "banging", "banged"],
    "bean": ["beans"],
    "onto": [],
    "attractive": [],
    "breath": ["breaths"],
    "cover": ["covers"],
    "empty": ["emptier", "emptiest"],
    "lonely": ["lonelier", "loneliest"],
    "painting": ["paintings"],
    "truly": [],
    "army": ["armies"],
    "avoid": ["avoids", "avoiding", "avoided"],
    "gang": ["gangs"],
    "land": ["lands", "landing", "landed"],
    "nerd": ["nerds"],
    "slap": ["slaps", "slapping", "slapped"],
    "appointment": ["appointments"],
    "dick": ["dicks"],
    "lesbian": ["lesbians"],
    "outfit": ["outfits"],
    "adventure": ["adventures"],
    "devil": ["devils"],
    "liar": ["liars"],
    "nurse": ["nurses"],
    "pot": ["pots"],
    "responsible": [],
    "salesman": ["salesmen"],
    "slow": ["slower", "slowest"],
    "wallet": ["wallets"],
    "commit": ["commits", "committing", "committed"],
    "example": ["examples"],
    "fake": ["fakes", "faking", "faked"],
    "obvious": [],
    "pirate": ["pirates"],
    "radio": ["radios"],
    "chase": ["chases", "chasing", "chased"],
    "due": [],
    "familiar": [],
    "homework": [],
    "birth": ["births"],
    "Canadian": [],
    "favorite": ["favorites"],
    "prefer": ["prefers", "preferring", "preferred"],
    "rub": ["rubs", "rubbing", "rubbed"],
    "sky": ["skies"],
    "basically": [],
    "coach": ["coaches"],
    "deliver": ["delivers", "delivering", "delivered"],
    "lab": ["labs", "laboratory", "laboratories"],
    "address": ["addresses"],
    "lift": ["lifts", "lifting", "lifted"],
    "concern": ["concerns", "concerning", "concerned"],
    "eleven": ["elevens"],
    "round": ["rounds"],
    "wish": ["wishes"],
    "guard": ["guards"],
    "contact": ["contacts"],
    "package": ["packages"],
    "travel": ["travels", "traveling", "traveled"],
    "sixty": ["sixties"],
    "anniversary": ["anniversaries"],
    "cent": ["cents"],
    "force": ["forces", "forcing", "forced"],
    "rest": ["rests", "resting", "rested"],
    "spread": ["spreads", "spreading"],
    "adorable": [],
    "ocean": ["oceans"],
    "percent": ["percents"],
    "shit": [],
    "wing": ["wings"],
    "above": [],
    "alcohol": ["alcohols"],
    "crash": ["crashes", "crashing", "crashed"],
    "insurance": ["insurances"],
    "nuclear": [],
    "pathetic": [],
    "row": ["rows"],
    "sight": ["sights"],
    "trash": ["trashes"],
    "available": [],
    "brave": ["braver", "bravest"],
    "climb": ["climbs", "climbing", "climbed"],
    "earn": ["earns", "earning", "earned"],
    "East": ["east"],
    "impress": ["impresses", "impressing", "impressed"],
    "league": ["leagues"],
    "online": [],
    "waste": ["wastes"],
    "within": [],
    "writer": ["writers"],
    "crowd": ["crowds"],
    "flip": ["flips", "flipping", "flipped"],
    "hug": ["hugs"],
    "drag": ["drags", "dragging", "dragged"],
    "funeral": ["funerals"],
    "literally": [],
    "lousy": ["lousier", "lousiest"],
    "opinion": ["opinions"],
    "pack": ["packs"],
    "spit": ["spits", "spitting", "spat"],
    "van": ["vans"],
    "behavior": ["behaviors"],
    "complain": ["complains", "complaining", "complained"],
    "recently": [],
    "stripper": ["strippers"],
    "subject": ["subjects"],
    "bright": ["brighter", "brightest"],
    "design": ["designed", "designing", "designs"],
    "general": [],
    "kidney": ["kidneys"],
    "result": ["results"],
    "strike": ["strikes"],
    "corn": ["corns"],
    "correct": [],
    "grandmother": ["grandmothers"],
    "hug": ["hugged", "hugging", "hugs"],
    "nightmare": ["nightmares"],
    "ours": [],
    "yellow": ["yellower", "yellowest"],
    "rise": ["risen", "rises", "rising", "rose"],
    "Christian": ["Christians"],
    "doughnut": ["doughnuts", "donut", "donuts"],
    "original": [],
    "position": ["positions"],
    "quarter": ["quarters"],
    "fool": ["fooled", "fooling", "fools"],
    "annoy": ["annoyed", "annoying", "annoys"],
    "can": ["cans"],
    "match": ["matches"],
    "play": ["plays"],
    "traffic": [],
    "actual": [],
    "banana": ["bananas"],
    "conference": ["conferences"],
    "lake": ["lakes"],
    "medical": [],
    "medicine": ["medicines"],
    "pray": ["prayed", "praying", "prays"],
    "shave": ["shaved", "shaven", "shaves", "shaving"],
    "tub": ["tubs"],
    "bake": ["baked", "bakes", "baking"],
    "option": ["options"],
    "South": [],
    "creepy": ["creepier", "creepiest"],
    "douchebag": ["douchebags"],
    "eventually": [],
    "interrupt": ["interrupted", "interrupting", "interrupts"],
    "library": ["libraries"],
    "rude": ["ruder", "rudest"],
    "ad": ["ads", "advertisement", "advertisements", "advertizement", "advertizements"],
    "danger": ["dangers"],
    "fourteen": ["fourteens"],
    "master": ["masters"],
    "math": ["maths"],
    "propose": ["proposed", "proposes", "proposing"],
    "Thursday": ["Thursdays"],
    "apart": [],
    "darling": ["darlings"],
    "gather": ["gathered", "gathering", "gathers"],
    "mostly": [],
    "support": ["supports"],
    "bubble": ["bubbles"],
    "energy": ["energies"],
    "heavy": ["heavier", "heaviest"],
    "laser": ["lasers"],
    "manage": ["managed", "manages", "managing"],
    "meanwhile": [],
    "network": ["networks"],
    "weapon": ["weapons"],
    "condition": ["conditions"],
    "copy": ["copies"],
    "female": [],
    "park": ["parked", "parking", "parks"],
    "quickly": [],
    "religion": ["religions"],
    "snow": ["snows"],
    "Tuesday": ["Tuesdays"],
    "version": ["versions"],
    "bomb": ["bombs"],
    "clear": ["cleared", "clearing", "clears"],
    "faith": ["faiths"],
    "innocent": [],
    "remove": ["removed", "removes", "removing"],
    "survive": ["survived", "survives", "surviving"],
    "bee": ["bees"],
    "bride": ["brides"],
    "cause": ["causes"],
    "fifth": ["fifths"],
    "several": [],
    "basketball": ["basketballs"],
    "downtown": [],
    "elephant": ["elephants"],
    "freak": ["freaks"],
    "wipe": ["wiped", "wipes", "wiping"],
    "arrest": ["arrested", "arresting", "arrests"],
    "bored": [],
    "bully": ["bullies"],
    "clock": ["clocks"],
    "indeed": [],
    "massage": ["massages"],
    "shape": ["shapes"],
    "skip": ["skipped", "skipping", "skips"],
    "strike": ["stricken", "strikes", "striking", "struck"],
    "dry": ["drier", "dryer", "driest", "dryest"],
    "remain": ["remained", "remaining", "remains"],
    "style": ["styles"],
    "surgery": ["surgeries"],
    "toe": ["toes"],
    "yard": ["yards"],
    "brilliant": [],
    "circle": ["circles"],
    "duty": ["duties"],
    "enemy": ["enemies"],
    "focus": ["foci", "focuses"],
    "lover": ["lovers"],
    "midnight": [],
    "simply": [],
    "Spanish": [],
    "boom": [],
    "describe": ["described", "describes", "describing"],
    "legal": [],
    "Mexican": ["Mexicans"],
    "powerful": ["powerfull", "powerfuller", "powerfuler", "powerfullest", "powerfulest"],
    "series": [],
    "wire": ["wires"],
    "candle": ["candles"],
    "diaper": ["diapers"],
    "direction": ["directions"],
    "divorce": ["divorces", "divorced", "divorcing"],
    "eighteen": ["eighteens"],
    "express": ["expressed", "expresses", "expressing"],
    "plastic": ["plastics"],
    "responsibility": ["responsibilities"],
    "starve": ["starved", "starves", "starving"],
    "united": [],
    "worker": ["workers"],
    "AIDS": [],
    "hope": ["hopes"],
    "immediately": [],
    "nowhere": [],
    "nowhere": [],
    "separate": ["separated", "separates", "separating"],
    "watch": ["watches"],
    "emotional": [],
    "hardly": [],
    "pilot": ["pilots"],
    "vampire": ["vampires"],
    "attitude": ["attitudes"],
    "balloon": ["balloons"],
    "exact": [],
    "frankly": [],
    "hip": ["hips"],
    "pet": ["pets"],
    "prank": ["pranks"],
    "announcement": ["announcements"],
    "effect": ["effects"],
    "escape": ["escaped", "escapes", "escaping"],
    "golden": [],
    "nipple": ["nipples"],
    "rough": ["rougher", "roughest"],
    "stick": ["sticks"],
    "trade": ["traded", "trades", "trading"],
    "twin": ["twins"],
    "waiter": ["waiters"],
    "architect": ["architects"],
    "beauty": ["beauties"],
    "mate": ["mates"],
    "official": [],
    "practice": ["practiced", "practices", "practicing"],
    "t-shirt": ["t-shirts"],
    "bug": ["bugs"],
    "crack": ["cracked", "cracking", "cracks"],
    "four hundred": [],
    "half": ["halves"],
    "contract": ["contracts"],
    "nail": ["nails"],
    "recognize": ["recognized", "recognizes", "recognizing"],
    "scientist": ["scientists"],
    "set": ["sets"],
    "shoulder": ["shoulders"],
    "successful": [],
    "turd": ["turds"],
    "view": ["views"],
    "basement": ["basements"],
    "degree": ["degrees"],
    "fortune": ["fortunes"],
    "hit": ["hits"],
    "invitation": ["invitations"],
    "oops": [],
    "professional": [],
    "search": ["searches"],
    "swing": ["swinging", "swings", "swung"],
    "train": ["trained", "training", "trains"],
    "weather": ["weathers"],
    "alarm": ["alarms"],
    "fun": ["funner", "funnest"],
    "kitty": ["kitties"],
    "nap": ["naps"],
    "practice": ["practices"],
    "precious": [],
    "product": ["products"],
    "rabbit": ["rabbits"],
    "role": ["roles"],
    "snack": ["snacks"],
    "sucker": ["suckers"],
    "tag": ["tags"],
    "chef": ["chefs"],
    "chew": ["chewed", "chewing", "chews"],
    "evidence": [],
    "fantasy": ["fantasies"],
    "operation": ["operations"],
    "puppy": ["puppies"],
    "rain": ["rains"],
    "spin": ["spinning", "spins", "spun"],
    "throat": ["throats"],
    "e-mail": ["e-mails", "e-mailing", "e-mailed", "email", "emails", "emailing", "emailed"],
    "present": ["presented", "presenting", "presents"],
    "reality": ["realities"],
    "saint": ["saints"],
    "top": [],
    "victim": ["victims"],
    "waitress": ["waitresses"],
    "booze": ["boozes"],
    "condom": ["condoms"],
    "director": ["directors"],
    "hunt": ["hunted", "hunting", "hunts"],
    "menu": ["menus"],
    "mystery": ["mysteries"],
    "quiet": [],
    "regret": ["regrets", "regretted", "regretting"],
    "technically": [],
    "ton": ["tons"],
    "attract": ["attracted", "attracting", "attracts"],
    "aware": ["awarer", "awarest"],
    "chest": ["chests"],
    "dentist": ["dentists"],
    "far": ["farther", "further", "farthest", "furthest"],
    "focus": ["focused", "focuses", "focusing", "focussed", "focusses", "focussing"],
    "illegal": [],
    "junior": [],
    "mouse": ["mice", "mouses"],
    "pencil": ["pencils"],
    "sentence": ["sentences"],
    "sixteen": ["sixteens"],
    "squeeze": ["squeezed", "squeezes", "squeezing"],
    "audition": ["auditions"],
    "lobster": ["lobsters"],
    "success": ["successes"],
    "terrorist": ["terrorists"],
    "asleep": [],
    "fashion": ["fashions"],
    "glove": ["gloves"],
    "item": ["items"],
    "recommend": ["recommended", "recommending", "recommends"],
    "tuna": ["tunas"],
    "warehouse": ["warehouses"],
    "Italian": ["Italians"],
    "lazy": ["lazier", "laziest"],
    "tank": ["tanks"],
    "whale": ["whales"],
    "zone": ["zones"],
    "honor": ["honored", "honoring", "honors"],
    "panic": ["panicked", "panicking", "panics"],
    "bachelor": ["bachelors"],
    "chain": ["chains"],
    "creature": ["creatures"],
    "diamond": ["diamonds"],
    "however": [],
    "image": ["images"],
    "parade": ["parades"],
    "rocket": ["rockets"],
    "solution": ["solutions"],
    "cable": ["cables"],
    "culture": ["cultures"],
    "forty-five": [],
    "garage": ["garages"],
    "male": [],
    "revenge": ["revenges"],
    "shrimp": ["shrimps"],
    "taco": ["tacos"],
    "thin": ["thinner", "thinnest"],
    "vote": ["votes"],
    "aside": [],
    "bum": ["bums"],
    "distract": ["distracted", "distracting", "distracts"],
    "DVD": ["DVDs"],
    "hehe": [],
    "humiliate": ["humiliated", "humiliates", "humiliating"],
    "locker": ["lockers"],
    "native": [],
    "performance": ["performances"],
    "policy": ["policies"],
    "pony": ["ponies"],
    "release": ["released", "releases", "releasing"],
    "stone": ["stones"],
    "woohoo": [],
    "advantage": ["advantages"],
    "basket": ["baskets"],
    "breakup": ["breakups"],
    "device": ["devices"],
    "garden": ["gardens"],
    "patient": ["patients"],
    "pink": ["pinker", "pinkest"],
    "represent": ["represented", "representing", "represents"],
    "thirteen": ["thirteens"],
    "treasure": ["treasures"],
    "amount": ["amounts"],
    "fart": ["farts"],
    "newspaper": ["newspapers"],
    "wind": ["winds"],
    "ashamed": [],
    "champion": ["champions"],
    "light": ["lighted", "lighting", "lights", "lit"],
    "per": [],
    "scout": ["scouts"],
    "guitar": ["guitars"],
    "mental": [],
    "sensitive": [],
    "twenty-four": [],
    "heat": ["heats"],
    "otherwise": [],
    "seventeen": ["seventeens"],
    "string": ["strings"],
    "wind": ["winds", "winding", "winded", "wound"],
    "downstairs": [],
    "impressive": [],
    "poop": ["poops"],
    "property": ["properties"],
    "skill": ["skills"],
    "dammit": [],
    "lead": ["leads"],
    "pancake": ["pancakes"],
    "slow": ["slowed", "slowing", "slows"],
    "stranger": ["strangers"],
    "charity": ["charities"],
    "freedom": ["freedoms"],
    "pour": ["poured", "pouring", "pours"],
    "stuff": ["stuffed", "stuffing", "stuffs"],
    "tradition": ["traditions"],
    "beef": ["beefs", "beeves"],
    "bite": ["bites"],
    "bullet": ["bullets"],
    "curious": ["curiouser", "curiousest"],
    "disaster": ["disasters"],
    "factory": ["factories"],
    "forest": ["forests"],
    "middle": [],
    "odd": [],
    "provide": ["provided", "provides", "providing"],
    "repeat": ["repeated", "repeating", "repeats"],
    "section": ["sections"],
    "subway": ["subways"],
    "choke": ["chokes", "choking", "choked"],
    "cowboy": ["cowboys"],
    "dirt": [],
    "frog": ["frogs"],
    "pumpkin": ["pumpkins", "punkin", "punkins"],
    "swallow": ["swallowed", "swallowing", "swallows"],
    "bacon": [],
    "clever": ["cleverer", "cleverest"],
    "competition": ["competitions"],
    "e-mail": ["e-mails", "email", "emails"],
    "heh": [],
    "lick": ["licked", "licking", "licks"],
    "mission": ["missions"],
    "pair": ["pairs"],
    "soap": ["soaps"],
    "tail": ["tails"],
    "tattoo": ["tattoos"],
    "activity": ["activities"],
    "bridge": ["bridges"],
    "detail": ["details"],
    "diet": ["diets"],
    "insult": ["insulted", "insulting", "insults"],
    "theme": ["themes"],
    "university": ["universities"],
    "champagne": ["champagnes"],
    "charming": [],
    "compare": ["compared", "compares", "comparing"],
    "gut": ["guts"],
    "map": ["maps"],
    "napkin": ["napkins"],
    "punch": ["punches"],
    "apply": ["applied", "applies", "applying"],
    "challenge": ["challenged", "challenges", "challenging"],
    "collect": ["collected", "collecting", "collects"],
    "cupcake": ["cupcakes"],
    "fridge": ["fridges"],
    "imagination": ["imaginations"],
    "joke": ["joked", "jokes", "joking"],
    "pad": ["pads"],
    "script": ["scripts"],
    "whip": ["whipped", "whipping", "whips", "whup", "whupped", "whupping", "whups", "whoop", "whoops", "whooping", "whooped"],
    "left": [],
    "affair": ["affairs"],
    "benefit": ["benefits"],
    "beyond": [],
    "book": ["booked", "booking", "books"],
    "citizen": ["citizens"],
    "grant": ["granted", "granting", "grants"],
    "junk": ["junks"],
    "magical": [],
    "prom": ["proms"],
    "schedule": ["schedules"],
    "studio": ["studios"],
    "value": ["values"],
    "invent": ["inventing", "invents", "invented"]
  }
  
  
  
  
  